[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
reqwest = { version = "=0.12.7", default-features = false }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs", "process", "io-std"] }
